version: '3.8'
services:
  technical-test-api:
    container_name: technical-test-api
    build: ./technical-test-api
    image: wbs-tech-test:latest
    ports:
      - 8080:8080
    network_mode: "host"
    #networks:
     # - spring-network
    depends_on:
      - db
  app:
    container_name: technical-test-frontend
    environment:
      - REACT_APP_HOST_IP_ADDRESS=http://localhost:8080/date/
    image: technical-test-frontend
    build:
      context: ./technical-test-frontend
      target: development
    ports:
      - 3000:3000
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data2
    network_mode: "host"
networks:
  spring-network:
    driver: bridge